apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reservations
  name: reservations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservations
  template:
    metadata:
      labels:
        app: reservations
    spec:
      containers:
        - image: reservations:v1.0.0
          name: reservations
          env:
            - name: POSTGRES_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: connectionString
            - name: KAFKA_BROKER
              value: 'kafka.kafka-ca1.svc.cluster.local:9092'
